#!/usr/bin/env python3
# -*- mode: python -*-

# This file is not installed; it's just to run annotations from inside a source
# distribution without installing it in the system.

import os
import sys
from kconfig import run


# Update PATH to make sure that annotations can be executed directly from the
# source directory.
def update_path():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    current_path = os.environ.get("PATH", "")
    new_path = f"{script_dir}:{current_path}"
    os.environ["PATH"] = new_path


update_path()
exit(run.main())
