#!/usr/bin/env python
# -*- mode: python -*-
# Manage Ubuntu kernel .config and annotations
# Copyright © 2022 Canonical Ltd.

import argparse
import sys
import json
from kconfig.annotations import Annotation, KConfig

VERSION = '0.1'

def make_parser():
    parser = argparse.ArgumentParser(
        description='Manage Ubuntu kernel .config and annotations',
    )
    parser.add_argument('--version', '-v', action='version', version=f'%(prog)s {VERSION}')

    parser.add_argument('--file', '-f', action='store',
                        help='Pass annotations or .config file to be parsed')
    parser.add_argument('--arch', '-a', action='store',
                        help='Select architecture')
    parser.add_argument('--flavour', '-l', action='store',
                        help='Select flavour (default is "generic")')
    parser.add_argument('--config', '-c', action='store',
                        help='Select a specific config option')

    ga = parser.add_argument_group(title='Action').add_mutually_exclusive_group(required=True)
    ga.add_argument('--query', '-q', action='store_true',
                        help='Query annotations')
    ga.add_argument('--export', '-e', action='store_true',
                        help='Convert annotations to .config format')
    ga.add_argument('--import', '-i', action='store',
                        metavar="FILE", dest='import_file',
                        help='Import a .config into annotations')
    ga.add_argument('--check', '-k', action='store',
                        metavar="FILE", dest='check_file',
                        help='Validate kernel .config with annotations')
    return parser

_ARGPARSER = make_parser()

def arg_fail(message):
    print(message)
    _ARGPARSER.print_usage()
    exit(1)

def do_query(args):
    a = Annotation(args.file)
    res = a.search_config(config=args.config, arch=args.arch, flavour=args.flavour)
    print(json.dumps(res, indent=4))

def do_export(args):
    if args.arch is None:
        arg_fail('error: --export requires --arch')
    a = Annotation(args.file)
    conf = a.search_config(config=args.config, arch=args.arch, flavour=args.flavour)
    if conf:
        print(a.to_config(conf))

def do_import(args):
    # Determine arch and flavour
    if args.arch is None:
        arg_fail('error: --arch is required with --import')

    # Merge with the current annotations
    c = KConfig(args.import_file)
    a = Annotation(args.file)
    a.update(c, args.arch, args.flavour)

    # Save back to annotations
    a.save(args.file)

def do_check(args):
    # Determine arch and flavour
    if args.arch is None:
        arg_fail('error: --arch is required with --check')

    # Parse target .config
    c = KConfig(args.check_file)

    # Load annotations settings
    a = Annotation(args.file)

    # Validate .config against annotations
    print(f"check-config: loading annotations from {args.file}")
    total = good = ret = 0
    for conf in c.config:
        # CONFIG_VERSION_SIGNATURE is dynamically set during the build
        if conf == 'CONFIG_VERSION_SIGNATURE':
            continue
        # Allow to use a different version of gcc
        if conf == 'CONFIG_CC_VERSION_TEXT':
            continue
        policy = a.config[conf] if conf in a.config else None
        expected = a.search_config(config=conf, arch=args.arch, flavour=args.flavour)[conf]
        if expected != c.config[conf]:
            print(f"check-config: FAIL: ({c.config[conf]} != {expected}): {conf} {policy})")
            ret = 1
        else:
            good += 1
        total += 1
    print(f"check-config: {good}/{total} checks passed -- exit {ret}")
    exit(ret)

def autodetect_annotations(args):
    if args.file:
        return
    # If --file/-f isn't specified try to automatically determine the right
    # location of the annotations file looking at debian/debian.env.
    try:
        with open('debian/debian.env', 'rt') as fd:
            args.file = fd.read().rstrip().split('=')[1] + '/config/annotations'
    except:
        arg_fail('error: could not determine DEBDIR, try using: --file/-f')

def main():
    args = _ARGPARSER.parse_args()
    autodetect_annotations(args)
    if args.query:
        do_query(args)
    elif args.export:
        do_export(args)
    elif args.import_file:
        do_import(args)
    elif args.check_file:
        do_check(args)

if __name__ == '__main__':
    main()
